#!/bin/bash

chown root:wheel /Library/LaunchDaemons/com.ChefKiss.DiskDbg.plist
chmod 644 /Library/LaunchDaemons/com.ChefKiss.DiskDbg.plist
chown -R root:wheel /Library/Scripts/disk-dbg
chmod -R 755 /Library/Scripts/disk-dbg

exit 0
