name: Build/Release

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: ./build.sh
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Universal
          path: build/DiskDbg.pkg
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          shopt -s nullglob
          files=(build/*.pkg)
          [ ${#files[@]} -gt 0 ] || { echo "No files found"; exit 1; }
          NOTES=$(awk '/^## '"${{ github.ref_name }}"'$/{flag=1; next} /^## v/{flag=0} flag' CHANGELOG.md | sed 's/^### /## /')

          [ -n "$NOTES" ] || {
            echo "No changelog entry found for ${{ github.ref_name }}"
            exit 1
          }

          echo "$NOTES" | gh release create "${{ github.ref_name }}" "${files[@]}" \
            -t "${{ github.ref_name }}" \
            --verify-tag \
            --fail-on-no-commits \
            --discussion-category Announcements \
            -F -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
